/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'Demo_F429_DDS' 
 * Target:  'Demo_F429_DDS' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* LVGL::LVGL&LVGL:lvgl:Essential@8.3.10 */
/*! \brief use lv_config_cmsis.h which will be pre-included */
#define LV_CONF_SKIP
#define LV_LVGL_H_INCLUDE_SIMPLE    1


#endif /* PRE_INCLUDE_GLOBAL_H */
