/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'Demo_F429_DDS' 
 * Target:  'Demo_F429_DDS' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* LVGL::LVGL&LVGL:lvgl:Demo:Widgets@8.3.10 */
/*! \brief enable demo:widgets support */
#define LV_USE_DEMO_WIDGETS         1
/* LVGL::LVGL&LVGL:lvgl:Essential@8.3.10 */
/*! \brief Enable LVGL */
#define RTE_GRAPHICS_LVGL
/* LVGL::LVGL&LVGL:lvgl:Extra Themes@8.3.10 */
/*! \brief use extra themes, widgets and layouts */
#define RTE_GRAPHICS_LVGL_USE_EXTRA_THEMES
/* LVGL::LVGL&LVGL:lvgl:GPU STM32-DMA2D@8.3.10 */
/*! \brief enable STM32 DMA2D */
#define LV_USE_GPU_STM32_DMA2D      1
/* LVGL::LVGL&LVGL:lvgl:Libs PNG@8.3.10 */
/*! \brief enable PNG support */
#define LV_USE_PNG          1
/* LVGL::LVGL&LVGL:lvgl:Libs sJPG@8.3.10 */
/*! \brief enable sJPG support */
#define LV_USE_SJPG         1


#endif /* RTE_COMPONENTS_H */
